### ISSUE TITLE
rule already registered

### ISSUE THREAD

**Issue by tijs** [tsuyoshiwada/react-drip-form#3]
When i reload a page that uses a drip form with a custom validation rule i get the error that the rule is already register and the component fails to load. Not sure how i should set everything up to prevent this...

My setup is as follows (redacted a bit for brevity):

```
import React from 'react';
import PropTypes from 'prop-types';
import { dripForm, Validator } from 'react-drip-form';

Validator.registerRule(
  'password_matches',
  (value, params, field, values) => value === values.password,
);

const EmailPasswordForm = dripForm({
  validations: {
    email: {
      required: true,
      email: true,
    },
    password: {
      required: true,
      min: 6,
    },
    password_confirm: {
      required: true,
      min: 6,
      password_matches: true,
    },
  },
  messages: {
    email: {
      required: 'Please enter your email address',
      email: 'This is not a valid email address',
    },
    password: {
      required: 'Please enter your password',
      min: 'Your password needs to be at least 6 characters',
    },
    password_confirm: {
      required: 'Please enter your password again',
      min: 'Your password needs to be at least 6 characters',
      password_matches: 'Enter the same password twice',
    },
  },
})(({ handlers, error, meta: { pristine, invalid, validating } }) => (
  <form onSubmit={handlers.onSubmit}>
    <FieldContainer>
      <Label htmlFor="email">
        Email *
      </Label>
      <Input type="text" id="email" name="email" />
    </FieldContainer>
    <FieldContainer>
      <Label htmlFor="password">
       Password *
      </Label>
      <Input type="password" id="password" name="password" />
    </FieldContainer>
    <FieldContainer>
      <Label htmlFor="password_confirm">
        Confirm Password *
      </Label>
      <Input type="password" id="password_confirm" name="password_confirm" />
    </FieldContainer>

    <Button
      color="blue"
      primary
      onClick={handlers.onSubmit}
      disabled={pristine || invalid || validating}
    >
       Register
    </Button>
    <Error error={error} />
  </form>
));
```

Fist time it loads it's fine. But when i use browser refresh on this form the console, sometimes not always strangely, says the asyncComponent failed to load due to password_confirm being defined already.

**Comment by wadackel** [comment]
Hi @tijs, Thank you for Issues.

Even if I tried the code your presented, no error occurred :cry:
If possible, it will be a great help if you share the minimal code (repository) that can reproduce the error :+1:

Thanks.

**Comment by tijs** [comment]
yeah sorry, i tried to some up with an easy way to reproduce it but could not either. the trouble is that we did not get always get the error. for now i've simply stopped using custom validations but that is of course not the best solution. is it also possible to simply pass a validation function directly to the validations config object instead of registering it? That might fix it for now as well.

**Comment by wadackel** [comment]
@tijs 

> it also possible to simply pass a validation function directly to the validations config object instead of registering it?

Yes :+1:
In `react-drip-form` you can pass the function directly to `validations` as follows:

```javascript
// Validator.registerRule(
//   'password_matches',
//   (value, params, field, values) => value === values.password,
// );

const EmailPasswordForm = dripForm({
  validations: {
    password_confirm: {
      // Pass a direct function
      password_matches: (value, params, field, values) => value === values.password,
    },
  },
  messages: {
    password_confirm: {
      password_matches: 'Enter the same password twice',
    },
  },
})(({ handlers, error, meta: { pristine, invalid, validating } }) => (
  <form onSubmit={handlers.onSubmit}>
    {/* ... */}
  </form>
));
```

**Comment by tijs** [comment]
Ah that is great! I will use that and close this for now then. If i run into anything similar again i will try and create a better reproducible issue next time!

**Comment by wadackel** [comment]
@tijs Thank you for confirmation :pray:  I am waiting for Issues :)
