### ISSUE TITLE
required if

### ISSUE THREAD

**Issue by Gi972** [tsuyoshiwada/react-drip-form#4]
Hello,

I try make a required if with two fieds and one of them would be fill. 
I try make a validator custom but when I clear a field the validator does not fire.

Can you help me please.

Thanks

**Comment by Gi972** [comment]
Hello,

I found just put implicit to -> false in Validator.registerRule

Nice plugin !!

**Comment by wadackel** [comment]
Hi @Gi972 Thanks for issues!
Issue is closed. Please report if there is a problem :smiley:
