### ISSUE TITLE
typescript definition 

### ISSUE THREAD

**Issue by Gi972** [tsuyoshiwada/react-drip-form#5]
Hello, 

Do you think add a definition file for typescript?

**Comment by wadackel** [comment]
Hi @Gi972, Thank you for issues.

I plan to add type definition in TypeScript and Flow in the future.
However, there are parts where the API has not been decided yet, so the addition seems to be a little later :cry:

**Comment by Gi972** [comment]
Ok ,
You hesitate between what and what?

**Comment by wadackel** [comment]
@Gi972 Currently `react-drip-form` uses Flowtype, but we plan to migrating to TypeScript.
For that reason, I'd like to distribute type definitions after migrating to TypeScript.
Because the work resources are limited, I want to avoid occurrence of duplicate work as much as possible.

Thanks :)
